version: "3.9"
services:
  nginx:
    image: public.ecr.aws/nginx/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  postgres:
    image: public.ecr.aws/docker/library/postgres:latest
    container_name: L2Art.db
    environment:
      POSTGRES_DB: l2art_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - l2art-network

  backend:
    build:
      context: ./back-end
      dockerfile: L2Art.Api/Dockerfile
    container_name: L2Art.backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
    networks:
      - l2art-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: development
    container_name: L2Art.frontend
    image: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --port 4200 --disable-host-check --poll 2000 --watch
    networks:
      - l2art-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - l2art-network

networks:
  l2art-network:
    driver: bridge

volumes:
  postgres_data:
