services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    container_name: L2Art.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email mouzy724@gmail.com -d l2art.duckdns.org --agree-tos

    # need to hide data after deploy on real server
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=l2art_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    container_name: L2Art.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end
      dockerfile: L2Art.Api/Dockerfile
    container_name: L2Art.backend
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
    restart: always


  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile 
      target: production 
    container_name: L2Art.frontend
    image: angular-prod
    ports:
      - "4200:4200"
  
volumes:
  postgres_data: