version: "3.9"

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:latest
    container_name: L2Art.db
    environment:
      POSTGRES_DB: l2art_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - l2art-network

  backend:
    build:
      context: ./back-end
      dockerfile: L2Art.Api/Dockerfile
    container_name: L2Art.backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - l2art-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: build
    container_name: L2Art.frontend
    image: angular-prod
    volumes:
      - frontend-build:/app/dist/frontend/browser
    networks:
      - l2art-network

  nginx:
    image: public.ecr.aws/nginx/nginx:alpine
    container_name: L2Art.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - l2art-network

networks:
  l2art-network:
    driver: bridge

volumes:
  frontend-build:
  postgres_data:
